@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Person(expert, "Expert", "Expert of the Sysops Squad")
Container(api, "API Application", "java and Spring MVC", "Delivers the static content and the internet banking single page application.")
System(scs, "Scheduling System")

Container_Boundary(api, "API"){

    Component(expertsvc, "Expert Service", "rest", "Returns experts with the related matching skills")
    Component(ticketsvc, "Ticketing Service", "rest", "Assign the ticket to the expert identified")
    Component(kbsvc, "Customer Service", "rest", "Obtains customer email or text")

}


Container_Boundary(ma, "Mobile Application") {
    Component(expertmod, "Expert Module", "Rest", "Updates the Expert availability")
    Component(ticketmod, "Ticketing Module", "Rest", "Retrives and update/completes the ticket")
    Component(kbmod, "Knowledge Base Module", "rest", "Searches, retrieves and adds to knowledge base")
    Component(sso, "Single Signon", "Security Services")

    Rel(expert, ma, "Uses")
}


@enduml
